### ISSUE TITLE
Trianglify "next" milestone

### ISSUE THREAD

**Issue by qrohlf** [qrohlf/trianglify#111]
Apparently I somehow managed to publish a 2.0.0 by accident from [this branch](https://github.com/qrohlf/trianglify/tree/bump_canvas_dep), hopefully it's working well for everybody but apologies to any users that got bit by any untested functionality! I'll do some final testing 

**This means a few things:**
- I'll be fast-tracking work on a v3 release, which is essentially just v2 with a bumped canvas dep (breaking change: node-canvas@latest no longer returns JSDOM canvas nodes, it uses its own thing now)
- I'll be continuing work on a v4 release, which is a near-rewrite to bring the project in line with modern JS best practice as well as add some new functionality.

**4.0.0 release checklist:**
- [x] Improved test suite
- [x] support the latest version of node-canvas, remove from optionalDependencies<sup>1</sup>
- [x] Default includeNamespace to true for SVG generation (https://github.com/qrohlf/trianglify/issues/74)
- [x] Switch away from gulp to something more modern
- [x] Add two new color functions: “sparkle”, “shadows”
- [x] Write Changelog
- [x] Update README
- [x] Update [live docs](http://qrohlf.com/trianglify/)
- [x] Update Trianglify.io
- [x] Merge `next` branch into `master`, announce release

-----
<sup>1</sup> I'm removing node-canvas from optionalDependencies because the default behavior of npm/yarn is to attempt to install all optionalDependencies, display any install errors, but not fail the full `npm install` operation if installation of an optionalDependency fails. This is proving to be extremely confusing for many users that are consuming the browser version of Trianglify, and seeing a bunch of install errors for a totally unnecessary node-related package when they try to `npm install`.

**Comment by qrohlf** [comment]
I'm going to punt on microbundle for now, it's proving to be a bit of a rabbit-hole trying to figure out the right way to package for both Node and web.
