### ISSUE TITLE
v0.2.0 post-release checklist

### ISSUE THREAD

**Issue by qrohlf** [qrohlf/trianglify#31]
- [x] check CDNJS to make sure it updated properly
- [x] push changes to NPM and update the docs page to pull in the latest NPM version
- [x] push changes to bower and make sure things are still behaving properly
